BEGIN;

SET TIMEZONE="Europe/Vilnius";

CREATE TABLE users (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	role SMALLINT NOT NULL,
	login TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL,
	passhash TEXT NOT NULL
);

CREATE TABLE users_bans (
	user_id INTEGER REFERENCES users(id) PRIMARY KEY,
	banner_id INTEGER REFERENCES users(id),
	date_created TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
	reason TEXT NOT NULL
);

CREATE TABLE rooms (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) NOT NULL,
	date_created TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
	is_public BOOLEAN NOT NULL,
	title TEXT NOT NULL
);

CREATE TABLE rooms_bans (
	room_id INTEGER REFERENCES rooms(id) PRIMARY KEY,
	banner_id INTEGER REFERENCES users(id),
	date_created TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,
	reason TEXT NOT NULL
);

CREATE TABLE rooms_users (
	room_id INTEGER REFERENCES rooms(id),
	user_id INTEGER REFERENCES users(id),
	date_created TIMESTAMP WITH TIME ZONE  NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY(room_id, user_id)
);

CREATE TABLE posts (
	id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	date_created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	date_updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	room_id INTEGER NOT NULL REFERENCES rooms(id),
	user_id INTEGER NOT NULL REFERENCES users(id),
	content TEXT
);

INSERT INTO users(date_created, role, login, name, passhash)
VALUES	('2020-12-08 15:25:00.000000+02', 1, 'testuser', 'TestUser', '$argon2id$v=19$m=102400,t=2,p=8$qV9bdvKsVxJejUK10n1wIA$G+vj8g9QtOt22rho8uFbNw');
INSERT INTO users(date_created, role, login, name, passhash)
VALUES	('2020-12-08 15:26:00.000000+02', 1, 'testuser2', 'TestUser2', '$argon2id$v=19$m=102400,t=2,p=8$NIn3gJluELjlR1S5nUDrrg$7S4lweZ1Qapvba6tTpvvwA');
INSERT INTO users(date_created, role, login, name, passhash)
VALUES	('2020-12-08 15:27:02.000000+02', 2, 'testadmin', 'TestAdmin', '$argon2id$v=19$m=102400,t=2,p=8$w2uayiE98FsiSTqyp8AtBA$iyy8RW2skes9vmQLvsOCbA');

INSERT INTO rooms(user_id, date_created, is_public, title)
VALUES	(1, '2020-12-08 15:32:00.000000+02', true, 'TestRoomPublic'),
		(1, '2020-12-08 15:33:00.000000+02', false, 'TestRoomPrivate'),
		(2, '2020-12-08 15:33:00.000000+02', false, 'TestUser2RoomPrivate');

INSERT INTO rooms_users(room_id, user_id, date_created)
VALUES (2, 2, '2020-12-08 16:30:00.000000+02'); -- Add user 2 to room 2 --

INSERT INTO posts(date_created, date_updated, room_id, user_id, content)
VALUES	('2020-12-08 17:30:34.075792+02', '2020-12-08 15:32:34.075792+02', 1, 1, 'test post in public test room'),
		('2020-12-08 17:30:42.285819+02', '2020-12-08 15:32:42.285819+02', 2, 1, 'test post in private test room');

COMMIT;